# Generated by Django 5.2 on 2025-04-09 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='balance',
            field=models.CharField(default=1, max_length=155, verbose_name='Баланс'),
            preserve_default=False,
        ),
    ]
