# Generated by Django 5.2 on 2025-04-09 13:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_balance_sessionauth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionauth',
            name='session_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
