# Generated by Django 5.2 on 2025-04-09 14:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_sessionauth_session_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionauth',
            name='session_id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
